### ISSUE TITLE
一部ユーザーでカード登録時に「アプリケーションに問題が発生しました」と表示され、カード登録が行えない。

### ISSUE THREAD

**Issue by Kansei** [payjp/payjp-react-native-plugin#169]
一部ユーザー（観測しているのは一人）で一部ユーザーでカード登録時に「アプリケーションに問題が発生しました」と表示され、カード登録が行えない問題が発生している。

![image](https://user-images.githubusercontent.com/28027378/109479538-d3750000-7abd-11eb-9483-eddecde982f0.png)

ユーザー様からのお問い合わせを受け、こちらでエラー調査を行ったのですが、そもそもエラーを再現することができず、原因を特定出来てない状況です。
もしよろしければ、考えうるエラーの原因を教えて頂きたです。

# 環境
- RN: v0.63.3
- payjp-react-native: 0.6.1
- 端末: iPhone12 mini(iOS14.4) 
- 登録しようとしたブランド: JCB

# コード
```js
import React, { useEffect } from "react";
import { Text, TouchableOpacity } from "react-native";
import { PayjpCore, PayjpCardForm } from "payjp-react-native";

const AddCreditCard = (props) => {
  const { createCard } = props;

  useEffect(() => {
    PayjpCore.init({
      publicKey: "本番公開鍵",
      locale: "ja",
    })
      .then(() => console.log("setup payjp"))
      .catch(() => console.log("error"));

    const cleanCardForm = PayjpCardForm.onCardFormUpdate({
      onCardFormProducedToken: (token) => {
        createCard(token.id)
          .then(() => PayjpCardForm.completeCardForm())
          .catch((e) => PayjpCardForm.showTokenProcessingError(e));
      },
    });

    return () => cleanCardForm();
  }, []);

  return (
    <TouchableOpacity
      onPress={() => PayjpCardForm.startCardForm()}
    >
      <Text>カードを追加</Text>
    </TouchableOpacity>
  );
};

export default AddCreditCard;
```

**Comment by yatatsu** [comment]
@Kansei フィードバックありがとうございます。エラー制御について一部のエラーのメッセージがSDKで丸められている可能性があるため改善します。こちらはReact NativeプラグインではなくSDK本体の https://github.com/payjp/payjp-ios 改善となる見込みで、修正後本プラグインにも反映します。

**Comment by yatatsu** [comment]
@Kansei [payjp-ios v1.5.1](https://github.com/payjp/payjp-ios/releases/tag/1.5.1) に対応したReact Nativeプラグイン v0.6.2をリリースいたしました。一部のエラーメッセージにエラーコードを含むよう改善しており加盟店様におけるトラブルシューティングにお役立ていただけます。

https://github.com/payjp/payjp-react-native-plugin/releases/tag/v0.6.2
