### ISSUE TITLE
[テスト/ライブ環境] アンドロイドでクレジットカードの登録ができない

### ISSUE THREAD

**Issue by Kansei** [payjp/payjp-react-native-plugin#251]
# 起きている問題
- クレジットカードを登録しようとすると、以下のようなエラーが発生します。
- iOSでは、同様の問題は発生しないので、アンドロイドのみで起きているようです。
- テスト環境、ライブ環境ともに同様のエラーが発生します。
- payjpの管理画面を見ると、カードトークンの作成はできてそうです。
- 6/18(金)の20時にユーザー様からのお問い合わせをうけ問題を発見しました。

<img width="300" alt="スクリーンショット 2021-06-19 17 41 27" src="https://user-images.githubusercontent.com/28027378/122637329-043e7b00-d129-11eb-81d0-480bb90a8ebd.png">

以下、テスト環境での動画です。ご確認下さい。
https://user-images.githubusercontent.com/28027378/122637064-947bc080-d127-11eb-9390-a14c1c2be159.mov

# 環境
- react-native: 0.63.4
- payjp-react-native: 0.5.3

もしこちらの実装方法に問題がありそうであればお知らせ下さい。
よろしくお願い致します。

# 補足
payjp-react-native: 0.6.3で正常に動作することを確認しました。

**Comment by yatatsu** [comment]
@Kansei フィードバックありがとうございます。
おそらくpayjp-android 1.5.0 未満のバージョンで発生する問題と推測されますので、
payjp-android 1.5.0 に対応した最新の payjp-react-native-plugin 0.6.3をご利用下さいますようお願いいたします。

**Comment by Kansei** [comment]
かしこまりました。
ご返信ありがとうございます。
