### ISSUE TITLE
[Android] Dupicate VERSION_NAME

### ISSUE THREAD

**Issue by pqv2210** [payjp/payjp-react-native-plugin#351]
When i install your library in my project and run with Android, i found error be like this image.
I tried to fix it by going into the directory and deleting this line but it doesn't seem to work when I run the ```npx react-native run-android``` command again.

![Screen Shot 2021-11-17 at 17 43 57](https://user-images.githubusercontent.com/64763689/142186569-f976db84-70e0-4d66-9bfa-388404ad7c25.png)

I use
```
react-native: 0.62.3
payjp-react-native: 0.6.3
```

Please tell me how can i fix this, thank you.

**Comment by Ppang0405** [comment]
I run example and it works. Could you try to run example?

**Comment by pqv2210** [comment]
@Ppang0405 i found a resolve for my problem.
Open ```.../node_modules/payjp-react-native/android/build.gradle```, find and delete line in buildConfig
```buildConfigField "String", "VERSION_NAME", "\"$pluginVersion\""```
