### ISSUE TITLE
How to set the language on PayjpCardForm

### ISSUE THREAD

**Issue by wbw20** [payjp/payjp-react-native-plugin#40]
Hello,

Thank you for releasing this library.  I am currently using it like so:

```
import React, { Component } from 'react'
import { PayjpCardForm } from 'payjp-react-native'

...

PayjpCore.init({ publicKey: 'my-key' })

...

class Checkout extends Component {
  onButtonPressed = () => {
    PayjpCardForm.startCardForm()
  }

  componentDidMount() {
    const unsubscribePayjpForm = PayjpCardForm.onCardFormUpdate({
      onCardFormProducedToken: async token => {
        ...
      }
    })
  }
  ...
}
```

Which gives me this card form:

![Screen Shot 2020-03-06 at 2 05 07 PM](https://user-images.githubusercontent.com/833121/76054358-c2c9a100-5fb3-11ea-84ca-534c2fe0a8ce.png)

However, I would like to set the language to Japanese.  Is that possible?  Currently it shows English regardless of the system language on iOS.

Thank you!

**Comment by yatatsu** [comment]
@wbw20 Thanks for your feedback.

We expect that the language of form will be come from the device setting.
And it can be changed by `Payjp.init` arguments as following.
We now support only two locales `ja` or `en`.

```javascript
// You can set locale regardless of the system language
PayjpCore.init({ publicKey: 'my-key', locale: 'ja' })
```

But actually, I reproduced language setting issue you reported.
I will check it very soon, thanks.

**Comment by wbw20** [comment]
Thank you!

**Comment by yatatsu** [comment]
@wbw20 

We identified that the problem roots back to the following two factors:
    1. The language of the interface is always chosen accordingly to the device language.
    2. The SDK was missing a localization setup.

Please follow these steps to set up localizations. This procedure should bring you changes akin to the following commit: b37d8b86eee4086ed31b7aaf14754032a7ccc2a0.

1. Add a Strings File named `Localizable.strings` to the project. (Figure 1.)
    * Figure 2 shows the expected result.

Figure 1.
<img width="1151" alt="figure_1" src="https://user-images.githubusercontent.com/949882/76082906-b6fbd000-5fef-11ea-95d5-9c89a31a7c79.png">

Figure 2.
<img width="1151" alt="figure_2" src="https://user-images.githubusercontent.com/949882/76082971-dd217000-5fef-11ea-89ce-e964c69bfcf0.png">​

2. Select `Localizable.strings`, then press the "Localize..." button in the right pane. (Highlighted in Figure 3.)

Figure 3.
<img width="1151" alt="figure_3_h" src="https://user-images.githubusercontent.com/949882/76083039-ffb38900-5fef-11ea-9130-e4b81854353f.png">

3. Switch to "Info" tab view of your project properties, then press the plus button under Localizations. (All steps highlighted in Figure 4.)

Figure 4.
<img width="1151" alt="figure_4_h" src="https://user-images.githubusercontent.com/949882/76083053-080bc400-5ff0-11ea-8400-64d94b22e388.png">

4. Activate `Localizable.strings` by selecting its checkbox. This will enable localization. (Figure 5.) 

Figure 5.
<img width="1151" alt="figure_5_h" src="https://user-images.githubusercontent.com/949882/76083065-0c37e180-5ff0-11ea-823e-40b44058a1a2.png">

5. You should now see `Localizable.strings (Japanese)` along with `Localizable.strings (English)` in the tree view. (Figure 6.)
    * End result

Figure 6.
<img width="1151" alt="figure_6_h" src="https://user-images.githubusercontent.com/949882/76083071-10fc9580-5ff0-11ea-9989-cd805e39758a.png">

I previously explained that the lauguage can be changed by setting the locale option in `Payjp.init`, however, this was not correct as the option only covered error messages provided by the API.
​
I hope this helps. Thanks.

**Comment by wbw20** [comment]
It works perfectly!  Thank you!
