### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleUtilities/Logger"

### ISSUE THREAD

**Issue by Kansei** [payjp/payjp-react-native-plugin#69]
# 発生している問題
`payjp-react-native(0.4.3)`を入れた状態で、`@react-native-firebase/app(8.3.1)`を入れて、
`pod install`すると以下の通り、iOSライブラリのバージョンの競合が起きてしまう。

```
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/Logger":
  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 8.3.1, which depends on
      Firebase/CoreOnly (~> 6.28.1) was resolved to 6.28.1, which depends on
        FirebaseCore (= 6.9.1) was resolved to 6.9.1, which depends on
          GoogleUtilities/Logger (~> 6.7)

    payjp-react-native (from `../node_modules/payjp-react-native`) was resolved to 0.4.3, which depends on
      GoogleUtilities/AppDelegateSwizzler (~> 6.5.2) was resolved to 6.5.2, which depends on
        GoogleUtilities/Logger (= 6.5.2)
```

# 原因
`GoogleUtilities/AppDelegateSwizzler`の`~> 6.5.2`に依存していることが原因
(`GoogleUtilities/AppDelegateSwizzler`のバージョンを`6.7`に上げると競合は解決された)

# お願い
依存する`GoogleUtilities/AppDelegateSwizzler`のバージョンを最新の`@react-native-firebase/app(8.3.1)`に対応していただけると幸いです。

はじめてのOSSへのイシュー投稿になるので、何か不足している情報などございましたらお知らせ下さい。
そもそもイシューに投稿すべき内容なのかどうかも分かってないですが、よろしくお願いします。

**Comment by yatatsu** [comment]
@Kansei フィードバックありがとうございます。
言及のとおり `GoogleUtilities/AppDelegateSwizzler` の依存は `~> 6.5.2` となっていて、プロジェクトで同じpodが6.6以上のバージョンが指定されている場合、依存が解決できなくなります。
最新のGoogleUtilitiesへの依存を含むプロジェクトで動作するよう対応しますので、アップデートをお待ち下さい。

**Comment by Kansei** [comment]
@yatatsu 
よろしくお願いします :bow:

**Comment by yatatsu** [comment]
@Kansei 
先程問題を修正したバージョン `0.4.4` をリリースしました。
https://github.com/payjp/payjp-react-native-plugin/releases/tag/v0.4.4

`GoogleUtilities` の今後の更新については、特に事情がない限り都度追従していくのが現時点の方針です。
フィードバック誠にありがとうございました。

**Comment by Kansei** [comment]
@yatatsu 
迅速な対応ありがとうございます 🙇
