### ISSUE TITLE
本番公開鍵をセットしてカード登録フォームを開くと「unkown error」と表示される

### ISSUE THREAD

**Issue by Kansei** [payjp/payjp-react-native-plugin#77]
# 起きてる症状
- 本番公開鍵をセットしてカード登録フォームを開くと「問題が発生しました」と表示され、カード追加ができなくなってる(iOS, Android共に)
- 10/20時点では正常に表示されていた
- payjp-react-nativeのパッケージを最新のものに更新しても変わらず
- 本番公開鍵を更新しても変わらず
- テスト公開鍵では正常に表示される(iOS, Android共に)

<img src="https://user-images.githubusercontent.com/28027378/97371019-b18f2500-18f3-11eb-8654-4edd84e0c371.png" width=250>

# 環境
- iOS: 14, 13
- Android: 10

# パッケージ
```
payjp-react-native: 0.4.5, 
react: 16.9.52,
react-native: 0.63.25
```

# ソースコード
```
import React, { useEffect } from "react";
import { Text, TouchableOpacity } from "react-native";
import { PayjpCore, PayjpCardForm } from "payjp-react-native";

const AddCreditCard = (props) => {
  const { createCard } = props;

  useEffect(() => {
    PayjpCore.init({
      publicKey: "本番公開鍵",
      locale: "ja",
    })
      .then(() => console.log("setup payjp"))
      .catch(() => console.log("error"));

    const cleanCardForm = PayjpCardForm.onCardFormUpdate({
      onCardFormProducedToken: (token) => {
        createCard(token.id)
          .then(() => PayjpCardForm.completeCardForm())
          .catch((e) => PayjpCardForm.showTokenProcessingError(e));
      },
    });

    return () => cleanCardForm();
  }, []);

  return (
    <TouchableOpacity
      onPress={() => PayjpCardForm.startCardForm()}
    >
      <Text>カードを追加</Text>
    </TouchableOpacity>
  );
};

export default AddCreditCard;
```

# PayJpアカウント
- メールアドレス: k.kogami@toypo.co.jp
- 利用サービス: PAY.JP Platform
- プラン: seed

こちらで考えれる、対応策は取ってみたものの解消されなかったのでイシューとして挙げさせていただきました。
対応方法等をご教授いただけますと幸いです。
また、不足してる情報等ありましたらお知らせください。

よろしくお願いします。

**Comment by yatatsu** [comment]
@Kansei フィードバックありがとうございます。
挙げていただいた事象について再現できましたので調査を進めています。

**Comment by yatatsu** [comment]
@Kansei こちらお問い合わせにてご返答致しましたとおり、SDKの問題ではないためこのissueはクローズします。本件のサポートが必要な場合、お問い合わせにて引き続き対応致します。
